### ISSUE TITLE
D-Pad Mapping Issue in Frontend

### ISSUE THREAD

**Issue by SirBossJam** [arianrhodsandlot/retro-assembly#11]
## Description

D-Pad configuration within the frontend (RetroAssembly) does not seem to function, but the other buttons map appropriately. I can map other buttons to the d-pad, but not the the d-pad on the controller. Nor can I map the controller d-pad to other buttons. I've tested a variety of wireless controllers in multiple different modes (2 from 8BitDo), a Switch Pro controller, and a wired USB SNES clone controller. All have more or less the same behavior. The emulator itself typically works fine, even with this issue.
### Steps to reproduce the bug

1. Connecting any controller, opening Settings menu, and selecting "Configure gamepads" and attempting to map the d-pad will present the issue.

### Environment information
- iOS 17.1.2 iPhone and iPad Safari
- Linux Fedora 39 Brave and Firefox
- Windows 10 Edge.

**Comment by arianrhodsandlot** [comment]
Thanks for your reporting. I just fixed this in #12 . Could you try again to see if it works as expected?

**Comment by SirBossJam** [comment]
Anytime! I tried a couple controllers and browsers, but as far as I can tell, the issue persists. The frontend recognizes the gamepad as soon as I press a directional button, but it just doesn't register on the mapping screen. Im happy to provide more info if I can. Fantastic work by the way :D
![Screenshot from 2023-12-27 18-06-55](https://github.com/arianrhodsandlot/retro-assembly/assets/66538223/7983f4ac-6ea3-4830-a01e-3d9be7c07341)

**Comment by arianrhodsandlot** [comment]
That's a bit weird...
I looked up [the FAQ of 8bit zero 2](https://support.8bitdo.com/faq/zero2.html) , they said:
> Does Dpad on Zero 2 function as a joystick or Dpad?
Its mapping by default is left joystick. However, it can be mapped as:
LEFT + Select : set Dpad as left analog stick

Did you set D-pad to act as a D-pad rather than a joystick manually? I guess D-pad acting as a joystick can be the root cause.

You can also try the mapping at [Gamepad Tester](https://hardwaretester.com/gamepad) to see if it works in a way that can be recognized by browsers.

**Comment by SirBossJam** [comment]
I guess I should have done a bit more testing. I am now able to map d-pad buttons. I didn't realize the default joystick mapping for these 8bitdo controllers. I also checked a DualShock 4 controller, which worked flawlessly (which I didn't test initially), so not sure if it also had the original issue. Definitely better now, thank you!
